### ISSUE TITLE
Post navigation v5 refactor checklist

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#105]
- [x] Extract Settings.js to top level config.js 
- [x] Refactor and document config.js as necessary
- [x] Move root navigation drawer to config.js
- [x] Replace Ionicons with something else from expo-vector-icons
- [x] move capo bottom of drawer
- [x] move About to bottom of drawer?
- [x] i18n tidying up
- [x] rename and document assets
- [x] home screen hero image
- [x] hide common image credit selector if config is not populated
- [x] create sample locale and config
- [x] step by step deployment docs

**Comment by galenriley** [comment]
Step by step docs will need improvement based off guinea pig experience, but this ever-expanding checklist is complete
